In [ ]:
import numpy as np
def primi(a):
    for i in range(2, a-1):
        if(a%i == 0):
            return False
    return True
arr = np.array([i for i in range(11) if primi(i)])
print(arr)


[0 1 2 3 5 7]


In [2]:
import numpy as np
a = np.arange(1, 20)
b = a[1:3]
a, b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([2, 3]))